try {
    callSomeFunc();
} catch (e) {
    console.log('Function does not exists')
}